ubuntu_amd64_task:
  container:
    image: ubuntu:jammy
  install_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake libz-dev libbz2-dev liblzma-dev libzstd-dev bzip2 zstd xz-utils
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure

freebsd_13_task:
  freebsd_instance:
    image: freebsd-13-0-release-amd64
  install_script:
    pkg install -y cmake bzip2 libzstd zstd lzma
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
      # run tests as user "cirrus" instead of root
    - pw useradd cirrus -m
    - chown -R cirrus:cirrus .
    - ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure
